SET MODE MySQL;

create table "announcement" ("id" integer generated by default as identity, "context" varchar(100), "create_time" timestamp, "create_user" varchar(255), "end_time" timestamp not null, "start_time" timestamp not null, "status" boolean not null, "title" varchar(30) not null, "employee_id" varchar(255), primary key ("id"));

create table "book" ("id" integer generated by default as identity, "author" varchar(100) not null, "intro" varchar(255), "isbn" varchar(30) not null, "language" varchar(20) not null, "name" varchar(100) not null, "page" varchar(10) not null, "photo_name" varchar(255), "photo_original_name" varchar(255), "price" integer not null, "pub_house" varchar(30) not null, "publish_date" timestamp not null, "purchase_date" timestamp not null, "status" integer not null, "type" varchar(20) not null, primary key ("id"));

create table "employee" ("id" varchar(255) not null, "department" varchar(100) not null, "email" varchar(50) not null, "name" varchar(20) not null, "password" varchar(100) not null, primary key ("id"));

create table "recommend" ("id" integer generated by default as identity, "auther" varchar(30) not null, "isbn" varchar(13) not null, "name" varchar(100) not null, "pub_house" varchar(30) not null, "publish_date" timestamp not null, "reason" varchar(255), "status" integer not null, "emp_id" varchar(255), primary key ("id"));

create table "records" ("id" integer generated by default as identity, "borrow_date" timestamp not null, "borrow_id" varchar(10) not null, "borrow_username" varchar(30) not null, "end_date" timestamp not null, "return_date" timestamp, "status" integer not null, "book_id" integer, "employee_id" varchar(255), primary key ("id"));

create table "reservation" ("id" integer generated by default as identity, "end_date" timestamp, "start_date" timestamp, "status" integer not null, "book_id" integer, "employee_id" varchar(255), primary key ("id"));

create table "schedule" ("id" integer generated by default as identity, "created_date" timestamp, "end_time" timestamp not null, "group" varchar(255), "job_name" varchar(255), "last_execute" varchar(2), "name" varchar(255) not null, "notice_time" time not null, "start_time" timestamp not null, "status" varchar(2) not null, "type" varchar(2) not null, "create_user_id" varchar(255), primary key ("id"));

alter table "announcement" add constraint "FK86e3cvaix5av5aq7ko4b9q3ak" foreign key ("employee_id") references "employee";
alter table "recommend" add constraint "FKpdg1o2ctujifx3avxy3tf62q2" foreign key ("emp_id") references "employee";
alter table "records" add constraint "FKe1e93h4wuawojaw1p6khw8ks0" foreign key ("book_id") references "book";
alter table "records" add constraint "FKx9avuvujxw21kpwpf5hekljv" foreign key ("employee_id") references "employee";
alter table "reservation" add constraint "FK64a41qc5bfy5efj1f60i1atgi" foreign key ("book_id") references "book";
alter table "reservation" add constraint "FKcg2x5nn27ahlxendt5v30krc" foreign key ("employee_id") references "employee";
alter table "schedule" add constraint "FKkvf1rgkfg07s5clx362apyjt3" foreign key ("create_user_id") references "employee";